export const ActionTypes = {
  SET_GENRE: 'SET_GENRE',
  SET_TAB: 'SET_TAB',
  SET_CURRENT_MOVIE: 'SET_CURRENT_MOVIE',
  SET_USER_DATA: 'SET_USER_DATA',
  SET_AUTHORIZATION_REQUIRED: 'SET_AUTHORIZATION_REQUIRED',
  SET_ERROR: 'SET_ERROR',
  SET_IS_SENT_STATUS: 'SET_IS_SENT_STATUS',
  SET_IS_SENDING_STATUS: 'SET_IS_SENDING_STATUS',

  LOAD_MOVIES: 'LOAD_MOVIES',
  LOAD_PROMO_MOVIE: 'LOAD_PROMO_MOVIE',
  LOAD_SIMILAR_MOVIES: 'LOAD_SIMILAR_MOVIES',
  LOAD_REVIEWS: 'LOAD_REVIEWS',
  LOAD_FAVORITES: 'LOAD_FAVORITES',

  UPDATE_FAVORITES: 'UPDATE_FAVORITES',

  POST_REVIEW: 'POST_REVIEW'
};
